### ISSUE TITLE
did you forget to commit CSS files?

### ISSUE THREAD

**Issue by felipesanches** [graphicore/nametableswapper#2]
I see no CSS files or folder on the static directory, but I see a /css url handler at app.yaml

**Comment by graphicore** [comment]
No, I think all files are there. The css is inline in the index.html file:

https://github.com/graphicore/nametableswapper/blob/master/app/static/index.html#L8

The url handler is probably there because I thought I'd use it, but I didn't in the end.

**Comment by felipesanches** [comment]
cool
